name: run

on:
  workflow_dispatch:
    inputs:
      year:
        required: true
        type: string
      month:
        required: true
        type: string
      from:
        required: true
        type: string
        default: '1'
      to:
        required: true
        type: string
        default: '31'


jobs:
  printLog:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18

      - name: Get dependencies
        run: go get -v -t -d ./...

      - run: |
          touch .env
          echo USERNAME=${{ secrets.USERNAME }} >> .env
          echo PASSWORD=${{ secrets.PASSWORD }} >> .env

      - name: Run main
        run: go run cmd/main.go -year=${{ github.event.inputs.year }} -month=${{ github.event.inputs.month }} -from=${{ github.event.inputs.from }} -to=${{ github.event.inputs.to }}

